### ISSUE TITLE
There are tools that are better than dreamweaver

### ISSUE THREAD

**Issue by Immortalin** [yoshiquest/reasons-for-clojurescript#1]
[This](http://pinegrow.com/) for example...

**Comment by yoshiquest** [comment]
Oh, wow, you actually commented on this old thing? Yeah, I know there are things better than that. It's just that this was made some months ago for a web design class where we HAD to use it.

And for future reference, these old projects are dead and abandoned for the most part. All of my attention is on forge-clj at this moment.
